# Configuration of the 'Comfort' plugin for Craftbukkit
# ------
# A list of all compatible Minecraft block and item IDs: http://bit.ly/akHPL2
# ------
# blocks: Set the blocks you want to be able to sit down on and their sitting-height . You have to use the IDs (and sub-IDs if needed) of the blocks. Example:
# Block-ID(:Block-sub-ID): sitting-height
# 53: 0.5
# 44:2: 0.3
# ------
# sneaking: If set to true, you have to sneak and rightclick to sit down on a seat.
# distance: The maximum distance between the seat (the center of the block) and the player to be able to sit down (to prevent glitching through walls, etc.).
# ------
blocks:
    '53:0': 0.5
    '53:1': 0.5
    '53:2': 0.5
    '53:3': 0.5
sneaking: true
distance: 2